



export const  ASYNCCHANGEPRICE = 'ASYNCCHANGEPRICE';
export const DOCPRICE = 'DOCPRICE';
export const GETWEATHERDATA = 'GETWEATHERDATA';
export const CHANGENUMBER = 'CHANGENUMBER';
export const GETCITYDATALIST = 'GETCITYDATALIST';
export const CITYDATAINITARRAY = 'CITYDATAINITARRAY';
export const CITYLISTDATA = 'CITYLISTDATA'